'''

'''

#   From alphabet[] a string of defined length is generated by arbitrary selection of alphabets and
#   stored in random_string[]
alphabet = [
            'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U',
            'V', 'W', 'X', 'Y', 'Z'
]

dictionary = [

]

from random import randint
from itertools import permutations


class LevelBuilder:

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.random_string = [
            alphabet[randint(0, 25)],
            alphabet[randint(0, 25)],
            alphabet[randint(0, 25)],
            alphabet[randint(0, 25)],
            alphabet[randint(0, 25)],

        ]
        self.valid_entries_for_level = []
        self.random_char_for_level = []

        for string in range(len(self.random_string)):
            random_string_permutations = permutations(self.random_string[:string + 1])
            for permutation in random_string_permutations:
                string = ''.join(permutation)
                perm_chars = []
                for char in permutation:
                    perm_chars.append(char)
                print(perm_chars)
                if string in dictionary and string not in self.valid_entries_for_level:
                    self.valid_entries_for_level.append(string)
                    for char in perm_chars:
                        if char not in self.random_char_for_level:
                            self.random_char_for_level.append(char)


LevelBuilder()
